export default [
  { locale: 'bg-BG', code: 'BL', name: 'Bulgarian' },
  { locale: 'cmn-Hant', code: 'CH', name: 'Chinese Mandarin (Traditional)' },
  { locale: 'ch-CHS', code: 'CHS', name: 'Chinese Mandarin (Simplified)' },
  { locale: 'ht-HT', code: 'CR', name: 'Haitian Creole' },
  { locale: 'en', code: 'E', name: 'English' },
  { locale: 'en-LR', code: 'ELI', name: 'Liberian English' },
  { locale: 'fr-FR', code: 'F', name: 'French' },
  { locale: 'fi-FI', code: 'FI', name: 'Finnish' },
  { locale: 'el-GR', code: 'G', name: 'Greek' },
  { locale: 'hu-HU', code: 'H', name: 'Hungarian' },
  { locale: 'hi-IN', code: 'HI', name: 'Hindi' },
  { locale: 'it-IT', code: 'I', name: 'Italian' },
  { locale: 'ilo-PH', code: 'IL', name: 'Iloko' },
  { locale: 'ja-JP', code: 'J', name: 'Japanese' },
  { locale: 'uk-UA', code: 'K', name: 'Ukrainian' },
  { locale: 'ko-KR', code: 'KO', name: 'Korean' },
  { locale: 'pt-LSB', code: 'LSB', name: 'Brazilian Sign Language' },
  { locale: 'es-LSE', code: 'LSE', name: 'Spanish Sign Language' },
  { locale: 'ro-RO', code: 'M', name: 'Romanian' },
  { locale: 'mg-MG', code: 'MG', name: 'Malagasy' },
  { locale: 'ms-MY', code: 'ML', name: 'Malay' },
  { locale: 'nl-NL', code: 'O', name: 'Dutch' },
  { locale: 'pl-PL', code: 'P', name: 'Polish' },
  { locale: 'wes-PGW', code: 'PGW', name: 'Pidgin (West Africa)' },
  { locale: 'he-IL', code: 'Q', name: 'Hebrew' },
  { locale: 'es-ES', code: 'S', name: 'Spanish' },
  { locale: 'et-EE', code: 'ST', name: 'Estonian' },
  { locale: 'sl-SI', code: 'SV', name: 'Slovenian' },
  { locale: 'sw-KE', code: 'SW', name: 'Swahili' },
  { locale: 'pt-POR', code: 'T', name: 'Portuguese (Brazil)' },
  { locale: 'tl-PH', code: 'TG', name: 'Tagalog' },
  { locale: 'ty-PF', code: 'TH', name: 'Tahitian' },
  { locale: 'tr-TR', code: 'TK', name: 'Turkish' },
  { locale: 'mg-TND', code: 'TND', name: 'Tandroy' },
  { locale: 'mg-TNK', code: 'TNK', name: 'Tankarana' },
  { locale: 'pt-TPO', code: 'TPO', name: 'Portuguese (Portugal)' },
  { locale: 'mg-TTM', code: 'TTM', name: 'Madagascar Sign Language' },
  { locale: 'tw-TW', code: 'TW', name: 'Twi' },
  { locale: 'ru-RU', code: 'U', name: 'Russian' },
  { locale: 'vi-VN', code: 'VT', name: 'Vietnamese' },
  { locale: 'mg-VZ', code: 'VZ', name: 'Vezo' },
  { locale: 'de-DE', code: 'X', name: 'German' },
  { locale: 'rw-RW', code: 'YW', name: 'Kinyarwanda' },
  { locale: 'sv-SE', code: 'Z', name: 'Swedish' },
];
