name: CI (Pull Requests)

on:
  pull_request:
    branches: [main, beta, alpha]

permissions:
  contents: read

jobs:
  test_unit:
    name: Run Test Units
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Use Node.js LTS version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: lts/Krypton

      - name: Install dependency
        run: npm ci

      - name: Build output
        run: npm run build

      - name: Check Locale Consistency
        run: npm run locale:check

      - name: Run Test Units
        run: npm run test

      - name: Browser version testing
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626
        with:
          command-prefix: '--'
          install: false
          browser: chrome
          build: npm run setup:client
          start: npm run start:client
